version: '3.8'

services:
  postgres:
    image: dockeraheman/multi_user_without_logs_db:v1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ipmanager
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ipmanager" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - ip-manager

  backend:
    image: dockeraheman/multi_user_without_logs_backend:v1
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/ipmanager
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ip-manager
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    image: dockeraheman/multi_user_without_logs_frontend:v1
    networks:
      - ip-manager
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  proxy:
    image: dockeraheman/multi_user_without_logs_proxy:v1
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend
    networks:
      - ip-manager
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  ip-manager:
    driver: bridge

volumes:
  pgdata:
